export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const TAGS_LOAD_SUCCESS = 'TAGS_LOAD_SUCCESS';
export const TAGS_LOAD_REQUEST = 'TAGS_LOAD_REQUEST';
export const TAGS_LOAD_FAILURE = 'TAGS_LOAD_FAILURE';

export const LISTINGS_LOAD_SUCCESS = 'LISTINGS_LOAD_SUCCESS';
export const LISTINGS_LOAD_REQUEST = 'LISTINGS_LOAD_REQUEST';
export const LISTINGS_LOAD_FAILURE = 'LISTINGS_LOAD_FAILURE';

export const DETAIL_LOAD_SUCCESS = 'DETAIL_LOAD_SUCCESS';
export const DETAIL_LOAD_REQUEST = 'DETAIL_LOAD_REQUEST';
export const DETAIL_LOAD_FAILURE = 'DETAIL_LOAD_FAILURE';

export const DETAIL_REMOVE_SUCCESS = 'DETAIL_REMOVE_SUCCESS';
export const DETAIL_REMOVE_REQUEST = 'DETAIL_REMOVE_REQUEST';
export const DETAIL_REMOVE_FAILURE = 'DETAIL_REMOVE_FAILURE';

export const LISTINGS_CREATE_SUCCESS =  'LISTINGS_CREATE_SUCCESS';
export const LISTINGS_CREATE_REQUEST =  'LISTINGS_CREATE_REQUEST';
export const LISTINGS_CREATE_FAILURE =  'LISTINGS_CREATE_FAILURE';

export const UI_RESET_ERROR = 'UI_RESET_ERROR';