export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const TAGS_LOAD_SUCCESS = 'TAGS_LOAD_SUCCESS';
export const TAGS_LOAD_REQUEST = 'TAGS_LOAD_REQUEST';
export const TAGS_LOAD_FAILURE = 'TAGS_LOAD_FAILURE';

export const LISTINGS_LOAD_SUCCESS = 'LISTINGS_LOAD_SUCCESS';
export const LISTINGS_LOAD_REQUEST = 'LISTINGS_LOAD_REQUEST';
export const LISTINGS_LOAD_FAILURE = 'LISTINGS_LOAD_FAILURE';